# Generated by Django 3.1.4 on 2021-01-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visiteur',
            fields=[
                ('pro_id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(blank=True, max_length=40, null=True)),
                ('email', models.CharField(blank=True, max_length=40, null=True)),
                ('page', models.CharField(blank=True, max_length=40, null=True)),
                ('test', models.CharField(blank=True, max_length=40, null=True)),
                ('test2', models.CharField(blank=True, max_length=40, null=True)),
                ('test3', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'register_visiteur',
                'managed': False,
            },
        ),
    ]
