# Generated by Django 3.1.4 on 2020-12-08 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visiteur',
            name='test3',
            field=models.CharField(default='', max_length=40, verbose_name='Test'),
        ),
    ]
